seperate docker installs from run
rpiml/okcollege-dev pull request #75
Opened 2016-12-14 05:16 UTC by andykais

take npm installs and pip installs out of `docker-compose.yml` and into `docker-init.yml`

to run okcollege-dev now:
on INIT `./bin/okcollege-init` (`docker-compose -f docker-init.yml`)
on each run `./bin/okcollege` (`docker-compose up`)

2016-12-14 06:27 UTC, seveibar requested changes
after docker-prod will accept

2016-12-14 08:52 UTC, seveibar approved these changes

2016-12-15 20:19 UTC, seveibar requested changes

2016-12-15 20:19 UTC, seveibar commented on bin/okc-psql
> +docker run -it --rm --net host postgres psql --command "CREATE DATABASE okcollege_dev;" -h localhost -U postgres
this file is for debugging the database, not creating a table in the database.

better with a separate bin file for the database creation or embed it directly in the docker-compose

2016-12-15 20:19 UTC, seveibar commented on bin/okcollege-init
> +docker-compose -f docker-init.yml up
yes

2016-12-15 20:19 UTC, seveibar commented on bin/okcollege-prod
> +docker-compose -f ./docker-prod.yml up
yes

2016-12-15 20:19 UTC, seveibar commented on docker-compose.yml
> +    command: "/bin/bash -c \"cd /usr/src/app && npm start\""
yes

2016-12-15 20:19 UTC, seveibar commented on docker-init.yml
> +    command: "/bin/bash -c \"cd /usr/src/app && pip install --upgrade pip && pip install -r requirements.txt --user\""
yes

2016-12-15 20:24 UTC, seveibar commented
I can't say I like the output being hidden, especially for `docker-init.yml`, I put the web-client on my system in a bad state because I wasn't sure if the init script was working or not and stopped it half way through (easily resolved, but emphasizes the problem).

2016-12-15 20:49 UTC, seveibar commented
This has been tested on my system and works well :+1:

2016-12-16 17:33 UTC, andykais commented
`okc-psql` and `okc-psql-init` files are separated, is that all you wanted?

2016-12-16 19:43 UTC, seveibar approved these changes

2016-12-16 19:43 UTC, merged